### PR TITLE
[FEAT] ReconnectWebsocketService

### PR DESCRIPTION
**Pull request by BigSteel**
### What does this PR do?
[FEATURE]: Reconnection mechanism

### Where should the reviewer start?
 - WebSocketService.java
 - ReconnectWebSocketService.java

### Why is it needed?
Unstable Web services or network jitter may cause frequent disconnections. The reconnection mechanism allows the business layer to ignore it

### CODE REVIEW

**Review by andrii-kl — COMMENTED** [review]
Rewriting or changing subscribe functionality is out of scope of the main idea of this PR. 
I would recommend to move these changes in to the next PR with a proposal description

**Comment by BigSteel** [comment]
ok. 
Thanks web3J for giving me a lot of help.
Do I add a policy to differentiate the reconnection of subscribe?
This strategy involves two types of processing logic
1. NONE. The default values, when the ws server link disconnected, stop all the subscription, and all requests will be thrown WebsocketNotConnectedException
2. AUTO_SUBSCRIBE. Subscription will be reconnected when websocket is reconnected.

Then I will complete the Unit test.

**Comment by gtebrean** [comment]
I might be wrong  but there is a PR that was merged that should solve this reconnection issue: https://github.com/web3j/web3j/pull/1645

**Comment by BigSteel** [comment]
> I might be wrong but there is a PR that was merged that should solve this reconnection issue: #1645
ReconnectWebsocketService extended functionality is built-in automatic reconnection

**Pull request closed without merging**
