### PR TITLE
Fix simultaneous requests for UNIX IPC

### PR DESCRIPTION
**Pull request by iongchun**
This PR attempt to solve the same problems described in #245, and #471, 
with opening one IPC connection for each request.

### CODE REVIEW

**Comment by fcorneli** [comment]
Why be so nice and keep the old constructors alive while we all know that they are wrong?
Sometimes hard breaking an API helps integrating developers more...

**Comment by iongchun** [comment]
Because they are public, and might still used by some simple/single-threaded applications unaffected by these issues? ;)

They are marked as deprecated anyway.
If this PR is merged, I could create another PR to remove them, which could be merged later (e.g., in next major version).

**Comment by iongchun** [comment]
@conor10 Yes. I finally find some time to get synchronized on rinkeby, and runs my test application with subscriptions of mined blocks and pending transactions, and simultaneous send some transactions. It runs without exceptions for many hours/blocks ;)

**Comment by conor10** [comment]
👍

**Pull request merged**
