### PR TITLE
Corrected incorrect sentence in modules.rst file

### PR DESCRIPTION
**Pull request by KoangHoYeom**
# What does this PR do?

I`m sorry for bad english

The word 'for' is used twice in the sentence in line 12.

### Where should the reviewer start?
*required*

### Why is it needed?

For perfect docs

Thank you! and I'm sorry that it's no big deal.

### CODE REVIEW

**Comment by iikirilov** [comment]
We are migrating our docs to markdown. Please see #979

**Comment by iikirilov** [comment]
@AlexandrouR did you apply this change already?

**Comment by AlexandrouR** [comment]
@KoangHoYeom Thanks for noticing that. 
@iikirilov I just fixed it.

**Comment by iikirilov** [comment]
thanks - this will be superseded by #979

**Comment by KoangHoYeom** [comment]
thank you for your review !

**Pull request closed without merging**
