### PR TITLE
FIx generateJavaFiles ArrayInStruct

### PR DESCRIPTION
**Pull request by 1329576606**
### What does this PR do?
FIx generateJavaFiles ArrayInStruct

### Where should the reviewer start?
FIx generateJavaFiles ArrayInStruct

### Why is it needed?
FIx generateJavaFiles ArrayInStruct

### CODE REVIEW

**Comment by gtebrean** [comment]
could you please add a test case?

**Comment by 1329576606** [comment]
> could you please add a test case?

There was already a unit test and I perfected it.
See the changes to this file codegen/src/test/resources/solidity/arraysinstruct/build/java/ArraysInStruct.java

**Comment by 1329576606** [comment]
> > could you please add a test case?
> 
> There was already a unit test and I perfected it. See the changes to this file codegen/src/test/resources/solidity/arraysinstruct/build/java/ArraysInStruct.java

The unit test method is this：
codegen/src/test/java/org/web3j/codegen/SolidityFunctionWrapperGeneratorTest.java L:150 testArraysInStructCompareJavaFileTest()

**Review by gtebrean — APPROVED** [review]
Approving this as is better handling the Struct wrapper generation.

**Pull request merged**
