### PR TITLE
Transaction decoder

### PR DESCRIPTION
**Pull request by fcorneli**
This PR allows you to decode raw transactions, both unsigned and signed.
Furthermore, you can verify the signature on decoded signed raw transactions and retrieve the chain id used during signing of the raw transaction.

### CODE REVIEW

**Comment by conor10** [comment]
@fcorneli Please can you provide a description for this PR?

**Comment by fcorneli** [comment]
Done.

**Comment by fcorneli** [comment]
Added padding fix for r and s, which can both be less than 32 bytes in size on some signatures.

**Comment by conor10** [comment]
👍

**Pull request merged**
