### PR TITLE
Add function to link binary with reference libraries in wrappers contract deployment

### PR DESCRIPTION
**Pull request by tonykwok1992**
### What does this PR do?
*Add function to link binary with reference libraries in wrappers contract deployment*

### Where should the reviewer start?
*All files*

### Why is it needed?
*Currently there is no way to deploy contract that have library unlinked, Adding this functionality so that we can link the bytecode library placeholder with library address before deployment*

### CODE REVIEW

**Comment by gtebrean** [comment]
@tonykwok1992  could you please add here a solidity smart contract example for this case?

**Comment by tonykwok1992** [comment]
Thanks for @cybernagl 's help to provide the solidity example. It is for the corresponding functionality in hardhat:
https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-ethers#library-linking

also some inspiration from etherjs https://github.com/ethers-io/ethers.js/issues/195

Currently this feature is not available in web3j

**Comment by NickSneo** [comment]
@tonykwok1992 The build is failing in local, these tests are failing -
```
SolidityFunctionWrapperGeneratorTest. testArraysInStructCompareJavaFileTest()
SolidityFunctionWrapperGeneratorTest. testEventParametersNoNamedCompareJavaFile()
SolidityFunctionWrapperGeneratorTest. testStructOnlyInArrayCompareJavaFile()
JavaClassGeneratorTest. initializationError
JavaParserTest. initializationError
MethodParserTest. initializationError
FunParserTest. initializationError
KotlinClassGeneratorTest. initializationError
KotlinParserTest. initializationError
```

I have rebased it to master, can you plz check failing tests?

**Review by NickSneo — CHANGES_REQUESTED** [review]
Do a spotlessApply, rebase to master and Fix the failing tests

**Comment by tonykwok1992** [comment]
> Do a spotlessApply, rebase to master and Fix the failing tests

All done

**Comment by tonykwok1992** [comment]
Made an enhancement to introduce `librariesLinkedBinary` so that we can maintain the original `static final BINARY` untouched, and we do not need to generate link libraries code when wrapper is generated without bin

**Review by NickSneo — APPROVED** [review]
LGTM

**Comment by tonyinf** [comment]
Rebased

**Comment by tonykwok1992** [comment]
rebased

**Pull request merged**
