### PR TITLE
Fix #919. Gen consistent privateKey with other eth libs

### LINKED ISSUE #919: Different privateKey generated by Mnemonic comparing to other libraries
To get privateKey from Mnemonic, I use: ECKeyPair.create(sha256(seed))

But it creates a different privateKey from the same mnemonic using TrustKeystore in iOS (TrustKeystore generates the correct privateKey comparing to https://iancoleman.io/bip39/)

I did some research and figure out that I need to do something with the configuration of how mnemonic is used. Can you please guide me. Thank you!

### PR DESCRIPTION
**Pull request by mawenpeng**
### What does this PR do?
Fix #919 to generate consistent eth private keys with other eth libs by mnemonics.

### Where should the reviewer start?
Please see the changes in the commit, and the comments of @razzbee in #919 .

### Why is it needed?
Inconsistency makes imcompatibilities.

### CODE REVIEW

**Comment by thor-ragnarok** [comment]
LGTM

**Comment by iikirilov** [comment]
No stale

**Comment by thor-ragnarok** [comment]
Not stale

**Comment by conor10** [comment]
This pull request has been mentioned on **Web3 Labs Community**. There might be relevant details there:

https://community.web3labs.com/t/web3j-v4-8-0-released/112/1

**Pull request merged**
