### PR TITLE
bytes, bytes1..32 fix; chainId is not restrictly required anymore (issues #1054, #1063)

### PR DESCRIPTION
**Pull request by avaness**
### What does this PR do?
it fixes https://github.com/web3j/web3j/issues/1054, https://github.com/web3j/web3j/issues/1063

### Where should the reviewer start?
- StructuredDataTest.java:155
- ValidStructuredDataWithBytesTypes.json - bytes and bytes3 datatypes

### Why is it needed?
StructuredDataTest.testBytestAndBytes32Encoding() fails on "bytes" and "bytes1..32" types

### CODE REVIEW

**Comment by iikirilov** [comment]
can you run `./gradlew spotlessApply` please

**Comment by avaness** [comment]
@iikirilov need your advise please

Seems I've already injected (and fixed) a bug with "bytes" type in the pulled code because no proper test coverage is provided by me to check hashes.

But I can't add correct test because current java implementation doesn't support absence of EIP712Domain.chainId which is not allowed by 0xProtocol specification still.

@iikirilov I need your advise. Would you guys mind if I add more flexible processing of "no chainId" in EIP712Domain schema to java's EIP712 StructuredDataEncoder.class implementation? Then I can add correct testing verification of hashed values right into tests.

``` 
*0xProtocol test message without EIP712Domain.chainId*
{
  "types": {
    "EIP712Domain": [
      {"name": "name", "type": "string"},
      {"name": "version", "type": "string"},
      {"name": "verifyingContract", "type": "address"}
    ],
    "Order": [
      { "name": "makerAddress", "type": "address" },
      { "name": "takerAddress", "type": "address" },
      { "name": "feeRecipientAddress", "type": "address" },
      { "name": "senderAddress", "type": "address" },
      { "name": "makerAssetAmount", "type": "uint256" },
      { "name": "takerAssetAmount", "type": "uint256" },
      { "name": "makerFee", "type": "uint256" },
      { "name": "takerFee", "type": "uint256" },
      { "name": "expirationTimeSeconds", "type": "uint256" },
      { "name": "salt", "type": "uint256" },
      { "name": "makerAssetData", "type": "bytes" },
      { "name": "makerAssetData", "type": "bytes" }
  	]
  },
  "primaryType": "Order",
  "domain": {
    "name": "0x Protocol",
    "version": "2",
    "verifyingContract": "0x12459c951127e0c374ff9105dda097662a027093"
  },
  "message": {
    "makerAddress": "0x9e56625509c2f60af937f23b7b532600390e8c8b",
    "takerAddress": "0xa2b31dacf30a9c50ca473337c01d8a201ae33e32",
    "feeRecipientAddress": "0xb046140686d052fff581f63f8136cce132e857da",
    "senderAddress": "0xa2b31dacf30a9c50ca473337c01d8a201ae33e32",
    "makerAssetAmount": 10000000000000000,
    "takerAssetAmount": 20000000000000000,
    "makerFee": 100000000000000,
    "takerFee": 200000000000000,
    "expirationTimeSeconds": 1532560590,
    "salt": 1532559225,
    "makerAssetData": "0xf47261b0000000000000000000000000e41d2489571d322189246dafa5ebde1f4699f498",
    "takerAssetData": "0x02571792000000000000000000000000371b13d97f4bf77d724e78c16b7dc74099f40e840000000000000000000000000000000000000000000000000000000000000063"
   }
}
```
```
*0xProtocol expected test message hash
0xccb29124860915763e8cd9257da1260abc7df668fde282272587d84b594f37f6
```

**Comment by iikirilov** [comment]
@avaness approved - please make the changes and I can review again

**Comment by avaness** [comment]
> @avaness approved - please make the changes and I can review again

changes are done, added fix for https://github.com/web3j/web3j/issues/1063 and proper 0xProtocol test for "bytes" type verification

**Comment by avaness** [comment]
@iikirilov please help. travis-ci can't deploy to your artifactory for a week. Unauthorized
```
Execution failed for task ':abi:uploadArchives'.
> Could not publish configuration 'archives'
   > Failed to deploy artifacts: Could not transfer artifact org.web3j:abi:jar:4.6.0-20191008.232552-59 
from/to remote (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: 
https://oss.sonatype.org/content/repositories/snapshots/org/web3j/abi/4.6.0-SNAPSHOT/abi-4.6.0-20191008.232552-59.jar. 
Return code is: 401, ReasonPhrase: Unauthorized.
```

**Comment by antonydenyer** [comment]
@avaness it looks like travis falls through the build script so I needed to put an explicit guard clause 
( :eyes:  https://github.com/web3j/web3j/commit/1ade5d6da6245802880fcdd07b92895183d5d28e )

@iikirilov please review again - then squash and merge if happy.

**Comment by avaness** [comment]
> @avaness it looks like travis falls through the build script so I needed to put an explicit guard clause
> (  [1ade5d6](https://github.com/web3j/web3j/commit/1ade5d6da6245802880fcdd07b92895183d5d28e) )

> @iikirilov please review again - then squash and merge if happy.

@iikirilov @conor10 please review, it's final version. Your travis ci was fixed by @antonydenyer

**Pull request merged**
