### PR TITLE
Updating android web3j with PRs added for 4.3.3 release 

### PR DESCRIPTION
**Pull request by MarkOSullivan94**
### What does this PR do?

Cherry picking two of the PRs which have to be merged in with Android branch

https://github.com/web3j/web3j/pull/901
https://github.com/web3j/web3j/pull/911

### Where should the reviewer start?

Not entirely sure if this is the approach which was desired in this issue here https://github.com/web3j/web3j/issues/1030 so thought I'd open with two cherry picked PRs first.

Next cherry picked PR I added caused some merge conflicts I guess this will do for now 😅 

Would be super useful if the PRs with the `merge-to-android` label all had info on what milestone / release it belonged to so it'd be easier to know what order they should be merged in

### Why is it needed?

To update android branch before next android release

### CODE REVIEW

**Comment by iikirilov** [comment]
@MarkOSullivan94 thank you for beginning this effort. The plan in my head right now is to merge all of the outstanding PRs and bring the android branch to feature parity with master before making a release (and skipping all the releases in the middle).

@antonydenyer Is it possible to auto-run CI for PRs going to android branch using java 6 - which is the current target. Having said that it might be a good time to question whether we want to upgrade the android branch to be java 8 and what the impact of that would be. Also it might make sense to spin the android stuff out into a separate repo?

**Comment by MarkOSullivan94** [comment]
@iikirilov opened this with a couple done initially to make sure I was approaching this the correct way. 

Would it be possible to get this merged into one of the existing android branch first and then the rest of the PRs merged later before a new Android release?

**Comment by antonydenyer** [comment]
> @antonydenyer Is it possible to auto-run CI for PRs going to android branch using java 6 - which is the current target. Having said that it might be a good time to question whether we want to upgrade the android branch to be java 8 and what the impact of that would be. Also it might make sense to spin the android stuff out into a separate repo?

Yes, you need to have a different https://github.com/web3j/web3j/blob/master/.travis.yml that does what you want.

**Comment by iikirilov** [comment]
#911 will need to be followed by #1055 before we can merge this.

**Pull request closed without merging**
