### PR TITLE
fix: make very useful method decode(...) public

### LINKED ISSUE #1591: Why are those decode methods in class TypeDecoder not public?
```java
    @SuppressWarnings("unchecked")
    static <T extends Type> T decode(String input, int offset, Class<T> type) {
        if (NumericType.class.isAssignableFrom(type)) {
            return (T) decodeNumeric(input.substring(offset), (Class<NumericType>) type);
        } else if (Address.class.isAssignableFrom(type)) {
            return (T) decodeAddress(input.substring(offset));
        } else if (Bool.class.isAssignableFrom(type)) {
            return (T) decodeBool(input, offset);
        } else if (Bytes.class.isAssignableFrom(type)) {
            return (T) decodeBytes(input, offset, (Class<Bytes>) type);
        } else if (DynamicBytes.class.isAssignableFrom(type)) {
            return (T) decodeDynamicBytes(input, offset);
        } else if (Utf8String.class.isAssignableFrom(type)) {
            return (T) decodeUtf8String(input, offset);
        } else if (Array.class.isAssignableFrom(type)) {
            throw new UnsupportedOperationException(
                    "Array types must be wrapped in a TypeReference");
        } else {
            throw new UnsupportedOperationException("Type cannot be encoded: " + type.getClass());
        }
    }
```
I have to use reflection when I want to decode the input data of an transaction.
https://github.com/web3j/web3j/issues/489
```java
    private <T extends Type> T decode(String input, int offset, Class<T> type) {
        try {
            Method refMethod = TypeDecoder.class.getDeclaredMethod("decode", String.class, int.class, Class.class);
            refMethod.setAccessible(true);
            return (T) refMethod.invoke(null, input, offset, type);
        } catch (Exception e) {
            throw new UnsupportedOperationException("Type cannot be encoded: " + type.getClass());
        }
    }
```
Or create a new class under the same package.
```java
package org.web3j.abi;

import org.web3j.abi.datatypes.Type;

public class TypeDecoderMethodExposer {
    public static <T extends Type> T decode(String input, int offset, Class<T> type){
        return TypeDecoder.decode(input, offset, type);
    }
}
```
But neither of them are elegant.
What's the purpose of making those methods non-public?

### PR DESCRIPTION
**Pull request by monperrus**
### What does this PR do?
fix: make very useful method  `decode(String input, int offset, Class<T> type)` public

Fix #1591

### Where should the reviewer start?
At the modifier change

### Why is it needed?
To have a better decoding API

### CODE REVIEW

**Review by rdovgan — APPROVED** [review]

**Review by hoanglamcoin — APPROVED** [review]

**Comment by mohamedelshami** [comment]
Hi @monperrus, could you please provide more context on the scenario where you would use `decode(String input, int offset, Class<T> type)`? would you be able to achieve what you're after with [decodeFunctionResult](https://github.com/web3j/web3j/blob/master/abi/src/main/java/org/web3j/abi/DefaultFunctionReturnDecoder.java#L44)?

By design, this is package protected and encapsulated from public access.

**Comment by monperrus** [comment]
The goal is to implement a `FunctionDecoder` for historical transaction inputs, as suggested by @iikirilov in https://github.com/web3j/web3j/pull/1206

It would also avoid using runtime reflection to bypass package visibility, as suggested by @ghqgfj to @githubityu in https://github.com/web3j/web3j/issues/489

**Comment by sanguivore-easyco** [comment]
> Hi @monperrus, could you please provide more context on the scenario where you would use `decode(String input, int offset, Class<T> type)`? would you be able to achieve what you're after with [decodeFunctionResult](https://github.com/web3j/web3j/blob/master/abi/src/main/java/org/web3j/abi/DefaultFunctionReturnDecoder.java#L44)?
> 
> By design, this is package protected and encapsulated from public access.

This would also provide basic support for our need of decoding function inputs before the relevant transaction has been submitted to the blockchain.

**Review by andrii-kl — APPROVED** [review]

**Comment by monperrus** [comment]
Thanks a lot @andrii-kl

**Pull request merged**
