### PR TITLE
Merge code from master branch to android branch

### PR DESCRIPTION
**Pull request by void-main**
I managed to merge code from master to android branch and changed the version to 3.4.0-android.

I really need this merge to make MnemonicUtils work on android.

### CODE REVIEW

**Comment by conor10** [comment]
@void-main I presume you've seen the build isn't working?

**Comment by void-main** [comment]
@conor10 yes, working on that

**Comment by void-main** [comment]
@conor10 fixed the failed test cases.

**Comment by dhruvi1kosmos** [comment]
@conor10  when can we expect updated version in android ?

**Comment by conor10** [comment]
@void-main Have you tried building on the command line with Gradle? There's Java 8 specific code in the merge (search for `->` in the diffs) which will break the backward compatibility.

**Comment by void-main** [comment]
@conor10 I tried to build with `gradlew build` and it actually passed.. But I did see some `->` in diff files, I'll take a look.

**Comment by void-main** [comment]
@conor10 Oh, boy, the websocket package is a mess, I have to replace *every* `CompletableFuture` with `Future`, I mean, kind of a re-write thing, gonna need some time..

**Comment by conor10** [comment]
No problem - your work is much appreciated.

**Comment by snazha-blkio** [comment]
This will be addressed in https://github.com/web3j/web3j/issues/769, closing this PR.

**Pull request closed without merging**
