### PR TITLE
Remove references to deprecated ChainId

### PR DESCRIPTION
**Pull request by kare**
### What does this PR do?
Replace Reference to `ChainId` with `ChainIdLong` and update `ChainId` and `ChainIdLong` Javadocs.

### Where should the reviewer start?
This is a small maintenance patch.

### Why is it needed?
It removes deprecation warnings.

### CODE REVIEW

**Comment by kare** [comment]
@AlexandrouR Thanks for merging my other PRs. I'm quite happy to fix this PR so it can be merged. Just let me know how.

cc: @iikirilov @conor10

**Review by SweeXordious — APPROVED** [review]
LGTM.
Sorry for the late reply.

**Comment by xaviarias** [comment]
Thanks @kare for your contribution. I think we should wait for a major release to remove deprecated code.

**Comment by kare** [comment]
@SweeXordious @xaviarias This PR is not removing classes or changing the API just replacing internal references to a deprecated class with a the new class.

**Pull request closed without merging**
