### PR TITLE
Allow usage of adding directory instead of one file to truffle generator

### PR DESCRIPTION
**Pull request by harveymatt**
I'm currently adding CI to my solidity development and now have a process in place but would like to make the process a little simpler:

Currently the flow looks as follows:
1. Create .json files using truffle ( managed by npm )
2. Use gradle to pull in the Web3J dependencies
3. Execute defined gradle ExecJava tasks with TruffleJsonFunctionWrapperGenerator.java to generate the java contract files one by one
4. Using the artifactory plugin to upload the packaged jar.

Step 3 would be a little bit simpler if I could generate all the contracts for a given solidity source directory 

(I'm aware this could also be done via a bash script or a more complicated gradle task but thought here seemed reasonable)

Keen to get thoughts..

### CODE REVIEW

**Comment by conor10** [comment]
It's certainly a valid idea. Would there be any issues running on directories such as [this](https://github.com/web3j/web3j/tree/master/codegen/src/test/resources/solidity/contracts), where files have a dependency on one another, or due to the nature of the Truffle metadata files, would this not actually be a concern?

**Comment by eepstein** [comment]
This is trivial to do with a Bash script. 
I can add mine to the docs. 
My vote is: no need.

**Comment by eepstein** [comment]
This is trivial to do with a Bash script. 
I can add mine to the docs. 
My vote is: no need.

**Comment by conor10** [comment]
I'm tempted to agree with @eepstein here. I think it could be tricky managing dependencies on other smart contract metadata located in the same directory too, as mentioned above.

**Comment by conor10** [comment]
Thanks for taking the time to submit @harveymatt.

**Pull request closed without merging**
