### PR TITLE
DO NOT MERGE add trace call many

### PR DESCRIPTION
**Pull request by frankisawesome**
### What does this PR do?
*required*

### Where should the reviewer start?
*required*

### Why is it needed?
*required*

### CODE REVIEW

**Comment by frankisawesome** [comment]
hey @conor10 any chance you can approve the CI run?
note that this is missing a test because the test file doesn't compile out of the box locally with `Cannot resolve method 'verifyResult' in 'RequestTest'`

**Comment by frankisawesome** [comment]
Any chance you could merge the revert so master is not broken and we can test out the build with a new PR @mohamedelshami ? Would also love some help getting started as the PR currently doesn't build and we're having some difficulties building locally, for context we're adding a Parity api missing that's very similar to an existing one.

**Comment by mohamedelshami** [comment]
@frankisawesome there was another issue with the build earlier which prevented this PR from completing the build.

I see the revert already merged. Let me know how else we can help to get this going.

**Comment by frankisawesome** [comment]
For the record I don't think the changes have been reverted, see https://github.com/web3j/web3j/commit/23ecc2a9974e0e0c081a5e5205f2d8cdfd9cadd1
the changes here are on master

**Comment by mohamedelshami** [comment]
@frankisawesome that's odd, I thought it would've been merged already after the revert, but it's now been pushed along with a more recent commit. 

Is it easier if you raise a new PR rolling forward the changes that you like to see in Partiy API?

**Pull request merged**
