### PR TITLE
MnemonicUtils fails to build WORD_LIST in android

### PR DESCRIPTION
**Pull request by ehanoc**
A similar fix for this was added in #498 but was merged into master and not into the android branch. 

This was highlighted in #595 

MnemonicUtilsTest, updated too

### CODE REVIEW

**Comment by M0rrisChang** [comment]
any reviewers?

**Comment by ehanoc** [comment]
> any reviewers?

Good point @M0rrisChang . I think a lot of people want a stable Android branch to develop on android and not wait for a release for fixes like these.

**Comment by snazha-blkio** [comment]
4.1.0-android has just been released and addresses this issue.

**Comment by magicgoose** [comment]
There's still a similar issue on 4.2.0-android - `inputStream` ends up = null, `populateWordList` throws an exception, this makes `MnemonicUtils` unusable.

There should be some more flexible and simple way to provide the word list, IMO.

**Pull request closed without merging**
